### ISSUE TITLE
Globalprotect logs parsing - pan os 9.1.x

### ISSUE THREAD

**Issue by Daavide** [PaloAltoNetworks/Splunk-Apps#100]
Hello,
I noticed that from pan os 9.1.x, globalprotect logs have been separated from system logs, but now they are not correctly parsed anymore.
https://docs.paloaltonetworks.com/pan-os/9-1/pan-os-release-notes/pan-os-9-1-release-information/features-introduced-in-pan-os-9-1/globalprotect-features.html#id1787EF00LF4

Is this a known problem? Can you provide a roadmap for this?

**Comment by subnet6** [comment]
Hello,

Has there been any movement on this? Just installed the latest version of the App and experiencing the same issues.

**Comment by paulmnguyen** [comment]
Resolved in version 6.3.1
