### ISSUE TITLE
Extractions for GlobalProtect Description items for ease of searching

### ISSUE THREAD

**Issue by jpbarron** [PaloAltoNetworks/Splunk-Apps#105]
### Is your feature request related to a problem?

The extractions for globalprotect events should ideally include 'Reason' data (auth failure message details) or other error messages broken out from the overall 'Description' field.

### Describe the solution you'd like

Currently I've set up some test inline extractions

^\d+\s+\d+\-\d+\-\d+\w+\d+:\d+:\d+\-\d+:\d+\s+\w+\-\w+\-\w+\d+\s+\-\s+\-\s+\-\s+\-\s+\d+,\d+/\d+/\d+\s+\d+:\d+:\d+,\d+,\w+,\w+,\d+,\d+/\d+/\d+\s+\d+:\d+:\d+,,\w+\-\w+\-\w+,\w+\-\w+,\d+,\d+,\w+,\w+,"\w+\s+\w+\s+\w+\s+\w+\s+\w+\.\s+\w+\s+\w+:\s+\d+\.\d+\.\d+\.\d+,\s+\w+\s+\w+:\s+\w+,\s+\w+\s+\w+:\s+\w+@\w+\.\w+,\s+\w+\s+\w+\s+\w+:\s+\w+\s+\w+\s+\d+\s+\w+\s+,\s+\d+\-\w+,\s+(?P<Reason>[^\,]+)
--

I think something like this should work:
[extract_globalprotect_failure_reason]
SOURCE_KEY =  description
REGEX = Reason: (?<failure_reason>[^,]+)

Other global protect message description data that would be helpful as individual extract items...
VPN type:
Client OS version:
error:
Source region:
Config name:  
Client OS: 
Machine Certificate CN : 
Host ID:

(Note Machine Certificate CN has a space in the message before the : which is not always obvious)

### Describe alternatives you've considered
Manually creating inline extractions but these should be in the default app config files.

### Additional context
Trying to build reports to send data to Help Desk to troubleshoot VPN issues.

**Comment by paulmnguyen** [comment]
This is legacy as GlobalProtect has it's own log type.
