### ISSUE TITLE
Missing Release Notes?

### ISSUE THREAD

**Issue by idev** [PaloAltoNetworks/Splunk-Apps#144]
Hello,

I miss some release notes for 6.4.0. Neither in the splunkbase nor in the documentation seems to be updated release notes.

Thank you

**Comment by btorresgil** [comment]
Hello, thanks for reaching out. The release notes are now on GitHub: https://github.com/PaloAltoNetworks/Splunk-Apps/releases/tag/v6.4.0 

We're using a new CI/CD process to do Splunk App releases. This is intended to let us do more frequent releases, so we can push out features and fixes faster with less chance of error. But unfortunately the SplunkBase API does not currently let us set the release note for a release. So the release notes can't live on SplunkBase. If you're a Splunk customer you can help us by reaching out to your Splunk rep and requesting this feature for the SplunkBase API.

**Comment by idev** [comment]
Ok, thank you!
Will contact devfeedback@splunk.com, they seem to be more aware regarding developer needs :)
