### ISSUE TITLE
PAN-OS 10.0.x logs for GP

### ISSUE THREAD

**Issue by saadm204** [PaloAltoNetworks/Splunk-Apps#156]
Global Protect logs do not appear in Splunk, hence dashboard for GP doesn't populate. A basic search for globalprotect on Splunk for PAN-OS 9.1.x shows the following:

<14>Dec 10 22:57:18 fw.host.net 1,2020/12/10 22:57:16,011901032278,GLOBALPROTECT,0,2305,2020/12/10 22:57:16,vsys1,gateway-tunnel-latency,tunnel,,,saad,,SM-PC,192.x.x.x,0.0.0.0,0.0.0.0,0.0.0.0,26c5e489-1a75-4b14-bfdb-4261b6bf0c28,7NDP1G2,5.1.5,,"",1,,,"Pre-tunnel latency: 14ms, Post-tunnel latency: 1ms",success,,0,,0,pagp-gw,90,0x0
•	host = 1xxxx
•	source = xxxxx
**•	sourcetype = pan:globalprotect**

but sourcetype = pan:globalprotect doesn't appear in search for devices sending logs for PAN-OS 10.0.x

**Comment by btorresgil** [comment]
Hi @saadm204 , thanks for opening this issue. Can you do a search to see if the 10.0.x GP logs are getting into the index at all? Perhaps something like this?

    sourcetype!=pan:globalprotect "GLOBALPROTECT"

If the logs show up but don't have the `pan:globalprotect` sourcetype, can you please share a sample of the 10.0 log like you did for the 9.1 log above? Thanks!

**Comment by saadm204** [comment]
Hi @btorresgil ,

I ran into an issue, restarted the splunk server and suddenly the dashboard populated. 

- I had intially set up the splunk server with input of firewall instead of log for two firewalls (one running 10.x and another 9.x)
- immediately I started seeing GP dashboard for 9.x firewall but not 10.x
- restarted the index for firewall with 10.x for a separate issue
- noticed the dashboard for 10.x start getting populated AND the globalprotect logs started to appear in the search as follows:

<14>Dec 14 00:37:39 CC-PA3220-FW.xxxx.com 1,2020/12/14 00:37:39,016201022459,GLOBALPROTECT,0,2560,2020/12/14 00:37:39,,gateway-hip-report,host-info,,,Blgndon,,4T4NQ13,16.29.37.44,0.0.0.0,172.1.4.157,0.0.0.0,,,4.1.12,,"",1,,,"",success,,0,,0,new_gateway,646334,0x0,2020-12-14T00:37:39.965-05:00,,,,,
host = x.x.x.x source = CC-PA3220-FW sourcetype = pan:globalprotect

thanks for the response, i'll close this as its not an issue on the release.

**Comment by btorresgil** [comment]
Sounds good, thanks for the follow up, and I'm glad to hear it's working now.
