### ISSUE TITLE
'All Incidents' dashboard counters 'Waiting for data...' in Splunk 8.1.2

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/Splunk-Apps#163]
## Describe the bug

Counters at the top of the All Incidents page toggle between 0 and 'Waiting for data...' over and over. This is not an issue on Splunk 8.0 and is first seen in Splunk 8.1.2. Unknown at this time if it affects other Splunk 8.1 versions besides 8.1.2.

## Expected behavior

The search should complete and return a counter number.

## Current behavior

Toggles back and forth between 0 and 'Waiting for data...'

## Possible solution

This dashboard will change in a coming app versions anyway, so that will resolve the problem. Unknown if this is fixable in currently released app versions as it uses a creative variable system to run the search when the dashboard loads. This technique was used to improve backward compatibility with older Splunk versions, but has now broken in 8.1.2. We might be able to change it to use another method, but unknown at this time.

## Steps to reproduce

1. Run the app in Splunk 8.1.2
2. Go to the All Incidents dashboard (no data necessary to reproduce)
3. Observe issue

## Screenshots

![2021-02-10_08-56-17 (1)](https://user-images.githubusercontent.com/4164289/107543472-2114e180-6b7e-11eb-97f2-1c69921e19fa.gif)

## Your Environment

- Version used: App 6.5.0
- Environment name and version Splunk 8.1.2
- Operating System and version (desktop or mobile): Tested on MacOS, likely affects all OS's

**Comment by Mufassa12** [comment]
Hi just @btorresgil just wanted to see if there would be any update on this? Regards Shaun

**Comment by JacobPEvans** [comment]
@Mufassa12, I just submitted https://github.com/PaloAltoNetworks/Splunk-Apps/pull/164v in case you need to get this fixed ASAP. It's a fairly trivial update.

**Comment by Mufassa12** [comment]
legendary, thanks for getting this update in.
