### ISSUE TITLE
cortex xdr logs not populating

### ISSUE THREAD

**Issue by saadm204** [PaloAltoNetworks/Splunk-Apps#173]
Forwarding logs from Cortex XDR to Splunk. Logs are received on splunk but not populating on any of the dashboard sections for Traps or Endpoint Security. Is this not supported yet?

**Comment by btorresgil** [comment]
We are working on Cortex XDR support in the Splunk App and Add-on. You can track progress at the Cortex XDR Pull Request: https://github.com/PaloAltoNetworks/Splunk-Apps/pull/166
