### ISSUE TITLE
eventtypes and tags are inconsistent

### ISSUE THREAD

**Issue by orion84** [PaloAltoNetworks/Splunk-Apps#193]
In the add-on (since version 7.0.0), there are several eventtypes referenced in tags.conf that do not exist in eventtypes.conf.

At least the following, but a further crosscheck may be in order:
pan_endpoint_change
pan_endpoint_alert
pan_endpoint_authentication
pan_endpoint_process

This causes splunk to throw visible warnings during search execution when a search references any of the related tags.

**Comment by bkcarter333** [comment]
I can concur with this issue. I notice it when running searches from within the Splunk Security Essentials app.
