### ISSUE TITLE
Dashboard.js broken on Splunk Cloud

### ISSUE THREAD

**Issue by M-Bates** [PaloAltoNetworks/Splunk-Apps#197]
When attempting to use App and Add-on in Splunk Cloud, dashboard.js is throwing javascript errors and failing.

Uncaught TypeError: mvc.createService is not a function
    at eval (eval at <anonymous> (dashboard.js:1), <anonymous>:40:21)
    at Object.execCb (eval at module.exports (dashboard.js:1), <anonymous>:1658:33)
    at Module.check (eval at module.exports (dashboard.js:1), <anonymous>:874:51)
    at Module.enable (eval at module.exports (dashboard.js:1), <anonymous>:1151:22)
    at Module.init (eval at module.exports (dashboard.js:1), <anonymous>:782:26)
    at eval (eval at module.exports (dashboard.js:1), <anonymous>:1424:36)

Attempts to rectify the error to allow a solution to be provided here have just raised further issues.

**Comment by DarthW1** [comment]
I have the same issue, and have gotten no assistance.  Has anyone resolved this?

**Comment by paulmnguyen** [comment]
Thanks for reporting this! I will get this in the next update.

**Comment by A11A110** [comment]
I am having the same issue with new version 7.0.4
![image](https://user-images.githubusercontent.com/101777321/158717953-6ed4b2eb-f19f-4fbd-8abd-427aa460684c.png)

**Comment by deviansg** [comment]
If this app has been upgraded from a previous version then there may be a legacy file called `dashboard.js` that was removed after version `7.0.2` of the app, but may still exist after upgrade.

The point of this file appears to have been to provide a warning if the associated Palo TA is not installed.

What makes this difficult to debug is the `dashboard.js` file will be automatically loaded into each dashboard within the PaloAlto app context. This means that even if the dashboard includes no JavaScript, this error will persist.

The reason its breaking looks to be incompatibility between it and the newer jQuery version (3.5) that is used by default when setting a dashboards version to 1.1. 

Alternatively, setting the dashboards to version 1.0 will also make this warning go away, but I would advise against it as it will make the dashboards dependent on an outdated version of jQuery.

Ultimately, removing the dashboard.js file should fix this error.
