### ISSUE TITLE
Error with the pancontentpack search command. No results returned and Return error code 1

### ISSUE THREAD

**Issue by bvarni** [PaloAltoNetworks/Splunk-Apps#222]
After upgrading the SplunkforPaloAltoNetworks app and the Splunk_TA_paloalto add-on to version 6.6.2 on Splunk Enterprise version 8.1.5, the pancontentpack search command fails. No results are returned.

The Firewall user is configured within the add-on, using the same credentials that worked on the previous version of the app and add-on. The search command also fails testing in the dev environment for version 7.0.3 of the app/add-on and Splunk Enterprise version 8.2.2.1.

**Splunk search:**
| pancontentpack panorama.myorg.net threats

**Error in the search UI window:**
External search command 'pancontentpack' returned error code 1. .

**Errors in search.log:**
11-02-2021 16:11:46.436 ERROR ScriptRunner [25740 phase_1] - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py panorama.myorg.net threats':  Traceback (most recent call last):
11-02-2021 16:11:46.436 ERROR ScriptRunner [25740 phase_1] - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py panorama.myorg.net threats':    File "/opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py", line 231, in <module>
11-02-2021 16:11:46.436 ERROR ScriptRunner [25740 phase_1] - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py panorama.myorg.net threats':      main()
11-02-2021 16:11:46.436 ERROR ScriptRunner [25740 phase_1] - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py panorama.myorg.net threats':    File "/opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py", line 220, in main
11-02-2021 16:11:46.436 ERROR ScriptRunner [25740 phase_1] - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py panorama.myorg.net threats':      csv = parse_threats(threat_xml)
11-02-2021 16:11:46.436 ERROR ScriptRunner [25740 phase_1] - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py panorama.myorg.net threats':    File "/opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py", line 167, in parse_threats
11-02-2021 16:11:46.436 ERROR ScriptRunner [25740 phase_1] - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py panorama.myorg.net threats':      a[key] = string_types(a[key])
11-02-2021 16:11:46.436 ERROR ScriptRunner [25740 phase_1] - stderr from '/opt/splunk/bin/python3.7 /opt/splunk/etc/apps/SplunkforPaloAltoNetworks/bin/panContentPack.py panorama.myorg.net threats':  TypeError: 'tuple' object is not callable
11-02-2021 16:11:46.956 ERROR script [25740 phase_1] - sid:1635869484.26 External search command 'pancontentpack' returned error code 1. .

**Previous app version and Splunk version (Splunk search completes as expected, returning results):**
App/Add-on version - 6.1.0
Splunk Enterprise version - 7.3.0

**Comment by paulmnguyen** [comment]
Hey bvarni, Thank you creating the issue. I am investigating this and will update you once we have a solution.

**Comment by paulmnguyen** [comment]
Fix is currently under review will merge and push a new release when review is complete.
