### ISSUE TITLE
PAN-OS 10.1.4 logs for GP

### ISSUE THREAD

**Issue by fabio1385** [PaloAltoNetworks/Splunk-Apps#231]
Hello, 

Global Protect logs do not appear in Splunk, hence dashboard for GP doesn't populate. 

PAN OS is version 10.1.4.
Splunk APP is version 7.0.4

I tried both with Source Type palo:log and palo:firewall

Thank you for your help

**Comment by paulmnguyen** [comment]
The logs should show up as sourcetype="pan:globalprotect".

**Comment by fabio1385** [comment]
Hello sorry for the delay, now the GP logs are working, I had to wait some time. 

Now I am suffering in configuring my dashboard because I have to better understand how to correctly configure the search strings in the various panels
