### ISSUE TITLE
External search command 'pancontentpack' returned error code 2

### ISSUE THREAD

**Issue by Skompelly6264** [PaloAltoNetworks/Splunk-Apps#237]
Hi I'm getting this error when I try to update the pancontentpacks "External search command 'pancontentpack' returned error code 2. Script output = "ERROR Unable to get apikey from firewall: local variable 'username' referenced before assignment ". unable to resolve this we wanted to update the threats_list lookup with cve table in it but we couldn't get this done, I opened a case with palo alto "02067515" Please let us know how to resolve this issue.

PAN-OS is 9.1.1
Splunk 8.2.3 Addon 7.0.4 latest version

**Comment by TLepingwell** [comment]
I know this is an old issue, but it turns out that the "Account Name" **_must_** be set to "Firewall" for the username and password combination being used to access a firewall.
