### ISSUE TITLE
A custom JavaScript error caused an issue loading your dashboard....." Palo Alto Networks Splunk App

### ISSUE THREAD

**Issue by Cliffcy** [PaloAltoNetworks/Splunk-Apps#246]
When going to the Threats and Activities dashboards in the Palo Alto Networks App on Splunk on-prem version  I get the error "A custom JavaScript error caused an issue loading your dashboard. I updated the Palo Alto Networks App in Splunk to the latest version 7.0.4 and still no fix.  Any solutions? All I have to do to replicate it is click any dashboard under the Threats or the Activities menus.

![image](https://user-images.githubusercontent.com/102500071/160323823-69fefd31-c2b5-4289-90ca-7303b654c74a.png)

- Environment name and version  : Chrome Version 99.0.4844.82 
- Operating System and version Window 10 pro 20H2

**Comment by Cliffcy** [comment]
The PANOS version is 9.0.5

**Comment by rfrey-splunk** [comment]
I'm seeing this same issue with v7.0.4 and v7.1.0 of the app running on Splunk v8.1.2

**Comment by paulmnguyen** [comment]
We are currently working with Splunk Cloud on this issue.

**Comment by aattelli91** [comment]
Hi Team
do we have any update for the above issue , as we are currently facing the same issue on 7.1.0
<img width="524" alt="image" src="https://user-images.githubusercontent.com/85359194/192513359-fdbc160b-0a23-4fa1-aa2b-0e34d7d019c6.png">


Thanks

**Comment by paulmnguyen** [comment]
Hey everyone, if you are seeing this message please uninstall and reinstall the app/add-on. The nature of Splunk upgrading leaves old files as they only replace files and not delete. You will need to remove the app/add-on and reinstall to remove the older files.

**Comment by siddharth-golchha** [comment]
> @paulmnguyen I see this error on brand new installation and freshly install add-on and app, running on SplunkCloud version 8.2+. This does not happen on regular on-prem installations. Javascript error:
> 
> ```
> TypeError: mvc.createService is not a function
>     at eval (eval at <anonymous> (dashboard_1.1.js:331:84868), <anonymous>:40:21)
>     at Object.execCb (eval at e.exports (common.js:556:18524), <anonymous>:1658:33)
>     at Module.check (eval at e.exports (common.js:556:18524), <anonymous>:869:55)
>     at Module.enable (eval at e.exports (common.js:556:18524), <anonymous>:1151:22)
>     at Module.init (eval at e.exports (common.js:556:18524), <anonymous>:782:26)
>     at eval (eval at e.exports (common.js:556:18524), <anonymous>:1424:36)
> ```


@dtwersky were you able to find a a resolution for this?
