### ISSUE TITLE
Pan:threat logs is not parsing correcly

### ISSUE THREAD

**Issue by burakatabay** [PaloAltoNetworks/Splunk-Apps#255]
## Describe the bug

Pan:threat logs is not parsing correctly after upgrade pan firewall 10.0 to 10.1 version.

## Expected behavior

I was expect after upgrade 10.0 to 10.1 some log field order the same. But in the field that was xff before, now sometimes coming category field. is that a normal ?

## Current behavior

Old pan firewall version 10.0 is currently sending logs correctly, but new version pan firewall as seen in picture is log order is not correct.
![image](https://user-images.githubusercontent.com/15073106/167097926-b5f14a1c-b468-45f6-8a47-f729a9687c3e.png)

## Steps to reproduce

1. Check log field order.

## Your Environment

- Splunk Palo Alto Network Add-On 7.1.0
- Splunk Enterprise 8.1.8
- Pan Firewall (10.0 && 10.1)

**Comment by paulmnguyen** [comment]
Could you please view a log where field is incorrect and provide that here for context. After reviewing the log documentation for 10.1 the order didn't change.

**Comment by Deepriver63** [comment]
I think I know what the issue is.  pan:threat sourcetype has the following subtypes:

data
file
packet
spyware
url (props/transforms geared for this type)
vulnerability

Each subtype changes the event data.  Since props and transforms are geared to URL, it breaks all the others.

**Comment by paulmnguyen** [comment]
Thanks for reporting this bug. This issue has been filed as a bug in PANOS and will get patched in a future release. No changes will be made in the Splunk add-on.

**Comment by burakatabay** [comment]
Thank you for information, I waiting new release.
