### ISSUE TITLE
Installation Instruction Misleading Where to Install TA

### ISSUE THREAD

**Issue by arcuseagles** [PaloAltoNetworks/Splunk-Apps#262]
The TA is not needed on Indexers if ingesting on a Heavy Forwarder. 
Installing on indexer causes error messages related to aperture, cortex xdr and minemeld settings missing.

**Comment by paulmnguyen** [comment]
Thank you for the information on the error messages. Closing this issue as we were told by Splunk Support to include the TA on indexers.
