### ISSUE TITLE
Version 7.1.0 - This app is not compatible with jQuery 3.5.

### ISSUE THREAD

**Issue by u2s1e0n2** [PaloAltoNetworks/Splunk-Apps#264]
Splunk Upgrade readiness scan shows app isn't JQuery 3.5 compatible. Do you have a fix for this?

**Comment by braies** [comment]
Hi Brian,

I noticed the same issue of aattelli91.
I'm using Splunk Enterprise 8.2.6.
This issue appeared after upgrade from splunk 7 to splunk 8.2.6
I also tried an upgrade to 9.0.1 in a dev environment, same issue.

I think this issue could be related to another issue: #264

**Comment by paulmnguyen** [comment]
Please uninstall app/add-on prior to installing version 8.0.0. Splunk does not remove old files when updating.
