### ISSUE TITLE
Update Add-on Builder to 4.1.0 for Splunk Cloud certification

### ISSUE THREAD

**Issue by btorresgil** [PaloAltoNetworks/Splunk-Apps#269]
### Is your feature request related to a problem?
App Inspect failures on TA:

`The Add-on Builder version used to create this app is below the minimum required version of 4.1.0.Please re-generate your add-on using at least Add-on Builder 4.1.0. File: default/addon_builder.conf Line Number: 4`

`Detected an outdated version of the Splunk SDK for Python (1.6.6). Please upgrade to version 1.6.16 or later.`

`Failures will block the Cloud Vetting.`

### Describe the solution you'd like

Upgrade Add-on Builder to 4.1.0.

**Comment by paulmnguyen** [comment]
Fixed in app/add-on version 8.0.0
