### ISSUE TITLE
When is the application going to be upgraded to be compatible with jQuery 3.5?

### ISSUE THREAD

**Issue by kelassal** [PaloAltoNetworks/Splunk-Apps#273]
Palo Alto Networks Add-on
Details
This app is not compatible with jQuery 3.5.
Version
7.1.0

Application Path
XX\Splunk\etc\apps\Splunk_TA_paloalto
Required Action
Do one of the following:
Confirm on the app's Splunkbase listing if this alert should be dismissed for this app version.
Petition the developer to update the app.
Uninstall the app from the app listing page.
Take ownership of the app and override existing code (not recommended).

**Comment by paulmnguyen** [comment]
Please make sure you uninstall the app before installing the latest version. The update does not remove old files which may include older versions of jquery.

**Comment by AuserB1** [comment]
Palo Alto Networks app (Version 8.0.1) is not compatible with jQuery 3.5.
