### ISSUE TITLE
Splunk_TA_paloalto Latest Version 8.0.0 Failed to load input page on Splunk Enterprise Version: 9.0.3

### ISSUE THREAD

**Issue by Bish0p404** [PaloAltoNetworks/Splunk-Apps#281]
## Describe the bug

Unable to initialize modular input "minemeld_feed" defined in the app "Splunk_TA_paloalto": Introspecting scheme=minemeld_feed: script running failed (exited with code 1)

## Expected behavior

Be able to load the input page smoothly.

## Current behavior

Failed to load the Inputs Page

## Possible Solution

:(

## Steps to reproduce

1. I did not try on other versions of Splunk.
2. Download and install Splunk_TA_PaloAlto latest version 8.0.0.
3. Thats IT

## Screenshots

![image](https://user-images.githubusercontent.com/123447033/215449262-27a23d2e-4792-4c55-800b-bb4b495a9ee8.png)

## Context

To achieve the Integrate between Cortex XDR and Splunk using the add-ons provided by Palo Alto and Icant do so without loading the Input.

Did try to downgrade the version of the add-on to one version which is 7.1.0 and it worked fine, So either you can check the minemeld_feed script to tell the difference and why this happened, or Splunk doesn't work probably with the new version.

## Your Environment

- Version used: Splunk Enterprise Version: 9.0.3 / Splunk_TA_paloalto Latest Version 8.0.0
- Environment name and version: Chrome109, Python 3.10.7
- Operating System and version: Ubuntu 22.10

**Comment by paulmnguyen** [comment]
Thank you for opening this issue. I am currently working on a resolution.
