### ISSUE TITLE
Apps version 8.0.x pushed to Splunkbase?

### ISSUE THREAD

**Issue by anderssynstad** [PaloAltoNetworks/Splunk-Apps#286]
Both https://splunk.paloaltonetworks.com/installation.html and github issues (https://github.com/PaloAltoNetworks/Splunk-Apps/issues/281) claims 8.0.x should be available on Splunkbase, but latest released version to Splunkbase appears to be 7.1.0.

**Comment by paulmnguyen** [comment]
Sorry for the confusion. I had to recall 8.0 due to an incompatibility issue with Splunk Cloud. We are working with Splunk App Inspect team to resolve the issues before we make another release.

**Comment by anderssynstad** [comment]
Thank you for clearing that up!
