### ISSUE TITLE
Splunk HEC PAN firewall events "_time" not matching configured "TimeGenerated" field 

### ISSUE THREAD

**Issue by jacobc8701** [PaloAltoNetworks/Splunk-Apps#307]
Hello there,

We are having a similar situation to: https://github.com/PaloAltoNetworks/Splunk-Apps/issues/200

From our Cortex Data Lake we are sending via HEC into SplunkCloud. However, the _time does not match TimeGenerated as expected and configured (please see screenshots)
<img width="902" alt="Screen Shot 2023-09-11 at 2 32 10 PM" src="https://github.com/PaloAltoNetworks/Splunk-Apps/assets/59471732/35ab1110-9411-44dc-9e8c-001619f4fb9b">

<img width="1637" alt="image006" src="https://github.com/PaloAltoNetworks/Splunk-Apps/assets/59471732/a5eceac3-3021-48ec-aee8-4a34626f3b14">

## Context

We want the _time to match TimeGenerated. 

## Your Environment

- Version used: SplunkCloud 9.0.2209 and Palo Alto Networks Add-on v8.1

Thanks!

**Comment by paulmnguyen** [comment]
Hey @jacobc8701 When you setup the HEC endpoint to forward logs from CDL include the argument  `auto_extract_timestamp=true`. It should automatically take the TimeGenerated field after you add this.

Reference documentation: https://docs.splunk.com/Documentation/Splunk/9.1.1/Data/HECRESTendpoints
