### ISSUE TITLE
Minemeld feeds URL inputs  not accepted

### ISSUE THREAD

**Issue by aldrimss** [PaloAltoNetworks/Splunk-Apps#308]
## Describe the bug

After upgrading from 7.1.0  to 8.1.0 when adding a minemeld feeds  the url isn't recognized as a valid URL.

## Expected behavior
The url should be accepted as the format is  "https://<feed_url>"

## Current behavior
An error "Remove feed URL protocal(http(s)://). Invalid Feed Url" is appearing and I can't validate my Minemeld inputs

## Possible solution

Fixing the regex used for validate url 

## Steps to reproduce

1. Downloading Palo alto networks add on
2. Configure the app
3. Entry menu
4.Create a new minemeld input

## Screenshots

![image](https://github.com/PaloAltoNetworks/Splunk-Apps/assets/145757521/00e118f7-d3f3-4a73-b989-90f9ce07f0d3)

## Context

Upgrading from 7.1.0 toward 8.1.0  my minemeld inputs didn't work anymore because of that

## Your Environment
Splunk_TA_paloalto : v8.1.0
Splunk  Cloud Version : 9.0.2303.202
Firefox

**Comment by aldrimss** [comment]
Found out the bug  :  needed to remove the "https://"  and those "-" in my node name.  Perhaps the regex should be changed/ error should be more explicit toward the user ?

**Comment by paulmnguyen** [comment]
Thanks for the feedback.
