### ISSUE TITLE
The splunk_ta_paloalto requests package is claiming a dependency on Older chardet and urllib3 versions, please update to new versions.

### ISSUE THREAD

**Issue by jcudilla** [PaloAltoNetworks/Splunk-Apps#316]
## The splunk_ta_paloalto requests package is claiming a dependency on Older chardet and urllib3 versions, please update to new versions.

Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!

## Current behavior

Current error:
Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (3.0.4) doesn't match a supported version!

## Possible solution

update to allow newer version of python modules

## Steps to reproduce

for example in /opt/splunk/etc/apps/Splunk_TA_paloalto/bin/splunk_ta_paloalto/aob_py3/solnlib/packages/requests/__init__.py
```
    # Check urllib3 for compatibility.
    major, minor, patch = urllib3_version  # noqa: F811
    major, minor, patch = int(major), int(minor), int(patch)
    # urllib3 >= 1.21.1, <= 1.25
    assert major == 1
    assert minor >= 21
    assert minor <= 25

    # Check chardet for compatibility.
    major, minor, patch = chardet_version.split('.')[:3]
    major, minor, patch = int(major), int(minor), int(patch)
    # chardet >= 3.0.2, < 3.1.0
    assert major == 3
    assert minor < 1
    assert patch >= 2
```

you are searching for chardet >= 3.0.2, < 3.1.0 however, we're on python3-chardet-5.1.0+dfsg-2. Similarly on urllib3 >= 1.21.1, <= 1.25 but we're already on python3-urllib3-1.26.12-1

## Your Environment

- Version used: Splunk_TA_paloalto v8.1.1
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): python3-3.11.2-1+b1, python3-chardet-5.1.0+dfsg-2, python3-urllib3-1.26.12-1
- Operating System and version (desktop or mobile): Debian GNU/Linux 12 (bookworm)

**Comment by paulmnguyen** [comment]
The aob_py3 directory is part of the Splunk Add-on Builder. We don't actually control what is in that directory. You may want to post this on the Splunk community to see if anyone from Splunk can respond to it. https://community.splunk.com/
