### ISSUE TITLE
GlobalProtect description fields

### ISSUE THREAD

**Issue by hcbomb** [PaloAltoNetworks/Splunk-Apps#43]
Hey guys!

I was reviewing some of the GP logs in our deployment to get a better sense of what is being captured.

I see that the following are extracted from the _description_ field:
- user
- src_ip
- agent_version
- agent_message

However, I took a quick pull of the different 'header' fields, and 'Message' doesn't seem to exist anymore.

Instead, here is a sample of what I'm able to pull from last 24h of GP logs:
- Auth type
- Client OS version
- Client version
- Config name
- Device name
- Login from
- Private IP
- Reason
- User name
- VPN type
- error

Only 4 of these are currently captured. Can we update for the rest of them? I'm particularly interested in the _Device name_, _Reason_, _Auth type_, and _error_ clauses. I can customize myself, but wanted to share w you guys as well.

Thanks!

**Comment by btorresgil** [comment]
Resolved in App/Add-on version 6.3.1 and PAN-OS 9.1.0. GlobalProtect logs are now a distinct log type with parseable fields supported by Splunk.
