### ISSUE TITLE
GlobalProtect Live or current users

### ISSUE THREAD

**Issue by pastorlibre** [PaloAltoNetworks/Splunk-Apps#99]
Hi is there a way to capture from logs who is currently logged in? I thought i could use sessions or logout but it doesn't seem to work that way. I am just looking to be able to do a dashboard and get the true number of users currently logged in.

**Comment by paulmnguyen** [comment]
Hey, Thanks for reaching out. In the app we have a GlobalProtect dashboard that checks for logins with out a logout in a time frame. The panel is called "Total users logged in". I'm closing this issue as it is not a feature request or a bug.
